language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: DEPENDENCIES='low'
    - php: 5.6
    - php: hhvm
    - php: 7.0
    - php: 7.1
    - php: 7.1
      env: DEPENDENCIES='dev'
  allow_failures:
    - env: DEPENDENCIES='dev'
  fast_finish: true

before_install:
  - if [ ${TRAVIS_PHP_VERSION:0:4} != "hhvm" ] && [ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]; then phpenv config-rm xdebug.ini; fi

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
   - bin/phpspec run --format=pretty
   - ./vendor/bin/phpunit --testdox
   - ./vendor/bin/behat --format=pretty

before_deploy:
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - chmod +x box.phar
  - mv box.phar box
  - EXPORT PATH=.:$PATH
  - make build-phar

deploy:
  provider: releases
  api_key:
    secure: kuNoMV1YPvdIQvKwf7NgYIFP4ZskFrZCRgq/+iTzP/vbyeB1mu/hyNkHtdl0Fj/2LpN1IcWm+C7hZ29NjQJGyrEkGnD8HWnUEn6k+FLhETg+BlckDTwSyhauXRIoaJeNUItNYFydG8MjEMBQgWQpsT6lWNSRAa3uC82K2zjQAx0=
  file: phpspec.phar
  skip_cleanup: true
  on:
    tags: true
    php: 5.6
    condition: $DEPENDENCIES != "low"
